### ISSUE TITLE
Improve failure management

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#328]
At the moment, following the reactive streams semantic, if something fails, the stream is stopped. This issue is about changing this behavior and allow:

- [x] Send the culprit message to a dead box (notify a bean) and continue the processing
- [x] Ignore the message, and continue the processing
- [x] Retry the message processing 
- [x] Allow configuring acknowledgment timeout
- [x] Allow rejecting a specific message (_nack_)

**Comment by geniusit** [comment]
+1 for that.
The `.recoverWithItem()` method is always called in the documentation : https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/model/model.html#processing-streams

It means that a fallback item is aways send in case of failure. But I m looking for a way not to send anything in case of failure (no fallback). 
The problem here is that the `.onFailure().invoke( failure -> log.error("Failed with " + failure.getMessage())` stops the streams with a stacktrace.

I m looking for a way to deal with the failure in the same way that I do when I `.subscribe()`

**Comment by cescoffier** [comment]
@geniusit See https://github.com/smallrye/smallrye-reactive-messaging/issues/566.

**Comment by cescoffier** [comment]
All tasks have been achieved - closing.
